### ISSUE TITLE
Integrations?

### ISSUE THREAD

**Issue by spekulatius** [mikecao/umami.is#4]
Hello @mikecao 

I was wondering if you are interested in a list of community-built integrations on the site.

I've built [one](https://github.com/spekulatius/vuepress-plugin-umami) and I guess others will build more over time.

Keen to hear what you think.

Cheers,
Peter

**Comment by mikecao** [comment]
I think have a huge list of links to integrations, projects, tutorials, etc on the site would be good.

**Comment by spekulatius** [comment]
Yeah, if you got more it would make a lot of sense. Do you want to add one or should look into it?

**Comment by mikecao** [comment]
I'll get it started and you can add any links you know of

**Comment by spekulatius** [comment]
Sounds good @mikecao

**Comment by mikecao** [comment]
Ok, here's the new section, https://umami.is/docs/useful-links

**Comment by spekulatius** [comment]
Cheers @mikecao
